config/routes.rb
Wiki::Application.routes.draw do

  resources :posts do
    get 'history', on: :member
  end

  resources :versions, only: :show

  resources :profiles, only: :show

  root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "about", to: "pages#about", as: "about"

  devise_for :users, controllers: {
    registrations: 'registrations', sessions: 'sessions' }

  namespace :admin do
    root "base#index"
    resources :users
  end

end

app/models/post.rb
class Post < ActiveRecord::Base

  has_paper_trail meta: {summary: :current_summary}

  paginates_per 20

  belongs_to :category
  belongs_to :user

  validates :category, presence: true
  validates :user, presence: true
  validates :summary, presence: true, on: :update
  validates :summary, length: { in: 1..60 }, on: :update

  def recent_siblings(n = 5)
    Post.where.not(id: self.id).where(category_id: self.category_id).order(updated_at: :desc).limit(n)
  end

  def full_title
    [category.title, title].join(" / ")
  end

  def category_title
    category.title
  end

  def content_length
    content.split(/\s+/).length rescue 0
  end

  def last_editor
    versions.count > 1 ?
      User.find(self.versions.last.whodunnit) : user
  end

  def current_summary
    self.summary
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :history]

  # GET /posts
  # GET /posts.json
  def index
    @category = Category.find(params[:category_id]) if params[:category_id].present?
    @posts = @category.present? ? @category.posts : Post.all
    @posts = @posts.page params[:page]
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  def history
  end

  # GET /posts/new
  def new
    @post = Post.new(category_id: params[:category_id])
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :category_id, :summary)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="row">
  <div class="col-sm-6">

  <%= form_for(@post) do |f| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title %>
      <div class="row">
        <div class="col-sm-12">
          <%= f.text_field :title, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :category %>
      <div class="row">
        <div class="col-sm-6">
          <%= select("post", "category_id", Category.all.collect {|p| [ p.title, p.id ] }, { include_blank: false, class: "form-control" }) %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :content %>
      <div class="row large">
        <div class="col-sm-12">
          <%= f.text_area :content, class: "form-control", rows: 5 %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-6">
        <%= f.submit "Submit", class: "btn btn-primary" %>
      </div>
    </div>

  <% end %>

  </div>
</div>

app/views/posts/_post.html.erb
<tr>
  <td><%= link_to post.title, post_path(post) %></td>
</tr>

app/views/posts/_version.html.erb
<tr>
  <td>
    <%= link_to version.created_at.strftime("%H:%M #{version.created_at.day.ordinalize} %B %Y"), (version.event == "create" ? post_path(version.item) : version_path(version)) %>
  </td>
  <td><%= version.summary %></td>
  <td><%= version_editor(version) %></td>
</tr>

app/views/posts/edit.html.erb
<h4>
  <%= best_in_place @post, :category_id, type: :select, collection: Category.all.map { |c| [c.id, c.title]}, display_as: :category_title %> / <%= best_in_place @post, :title, type: :input %>
  <small>Click to edit category or title</small>
</h4>
<hr class="dotted">

<div class="row">
  <div class="col-sm-6">
    <p>Remember, the name of the game is make each entry as short, succinct and concise as possible.</p>
    <p>You need to use your superior understanding of the topic at hand to cut the heart of the matter. We reckon: You only truly understand something if you can explain clearly to a five year old.</p>
  </div>
</div>

<div class="row">
  <div class="col-sm-6">

    <%= form_for(@post) do |f| %>

      <div class="form-group">
        <%= f.label :content %>
        <div class="row large">
          <div class="col-sm-12">
            <%= f.text_area :content, class: "form-control", rows: 5 %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :summary %>
        <div class="row">
          <div class="col-sm-12">
            <%= f.text_field :summary, class: "form-control",
              placeholder: @post.errors[:summary].present? ? "You need to enter an edit summary!" : "What did you change? Make a note of it here",
              limit: 60, value: '' %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12">
          <div class="col-sm-6">
            <small>
              Created by <%= link_to @post.user.username, profile_path(@post.user.id) %> on <%= @post.created_at.to_date.strftime("%d/%m/%y") %><br/>
              Last edited by <%=  link_to @post.last_editor.username, profile_path(@post.last_editor.id) %> on <%= @post.updated_at.to_date.strftime("%d/%m/%y") %><br/>
              <%= link_to pluralize(@post.versions.count, 'edit'), history_post_path(@post) %> in total.
            </small>
          </div>
          <%= f.submit "Submit", class: "btn btn-lg btn-primary pull-right" %>
        </div>
      </div>

    <% end %>

  </div>
</div>

app/views/posts/history.html.erb
<% title "Nutshell - #{@post.title} revision history" %>

<h3><%= @post.full_title %> - Revision History</h3>
<hr class="dotted">

<table class="table table-striped">
  <%= render partial: 'version', collection: @post.versions.order(created_at: :desc), as: :version %>
</table>

app/views/posts/index.html.erb
<% if @category %>
  <% title("Nutshell - #{@category.title}") %>
  <h3><%= @category.title %></h3>
  <hr class="dotted"/>
<% end %>

<table class="table table-striped">

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post_path(post) %></td>
      </tr>
    <% end %>
  </tbody>

</table>

<%= paginate @posts %>

app/views/posts/new.html.erb
<h4>Add a new entry</h4>

<%= render 'form' %>

app/views/posts/show.html.erb
<% title "Nutshell - #{@post.title}" %>

<h3><%= @post.full_title %><span class="pull-right"><small><%= link_to 'Edit this entry', edit_post_path(@post), class: ("authenticatable" unless signed_in?) %></small></span></h3>
<hr class="dotted">

<p class="lead"><%= markdown @post.content %></p>

<br/>

<div class="row">
  <div class="col-sm-4">
    <small>
      Created by <%= link_to @post.user.username, profile_path(@post.user.id) %> on <%= @post.created_at.to_date.strftime("%d/%m/%y") %><br/>
      Last edited by <%= link_to @post.last_editor.username, profile_path(@post.last_editor.id) %> on <%= @post.updated_at.to_date.strftime("%d/%m/%y") %><br/>
      <%= link_to pluralize(@post.versions.count, 'edit'), history_post_path(@post) %> in total.
    </small>
  </div>
</div>

<br/>

<div class="row">
  <div class="col-sm-6">
    <span class="pull-right">This entry is <%= pluralize @post.content_length, 'word' %>. Think you can make it more concise? <%= link_to "Edit it", edit_post_path(@post), class: ("authenticatable" unless signed_in?) %>.</span>
  </div>
</div>

<br/><br/>
<h4>Other entries in <%= @post.category.title %>:</h4>
<hr/>

<ul>
  <% @post.recent_siblings.each do |post| %>
    <li><%= link_to post.title, post_path(post) %></li>
  <% end %>
</ul>

<hr/>